name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Upd repos and packages
#      run: sudo apt-get update && sudo apt-get upgrade
#
#    - name: Install prerequisites for canvas package
#      run: sudo apt-get install build-essential libc6-udeb binutils libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Install dependencies
      run: npm ci

    - uses: iCrawl/action-tsc@v1

#    - name: Run tests
#      run: npm test -- --ci
